### ISSUE TITLE
Such Troll. Much Wow.

### ISSUE THREAD

**Issue by Andrew-Quebe** [WirelessBytes/fullscreenrickroll#1]

**Comment by danielhickman** [comment]
![](http://media.giphy.com/media/KsgLFgQp7Elj2/giphy.gif)
![](http://i0.kym-cdn.com/photos/images/newsfeed/000/614/631/54b.gif)
![](http://weknowgifs.com/wp-content/uploads/2013/03/billy-dee-williams-clapping.gif)
![](http://38.media.tumblr.com/4dcb32e3d919705576bcf2c4263a5f8c/tumblr_n9uqy2UcXD1rrx588o1_400.gif)
![](http://weknowgifs.com/wp-content/uploads/2013/03/obama-clapping-gif.gif)
![](http://3.bp.blogspot.com/-gCo44AmAGLk/UWgP9Ot56nI/AAAAAAAAQ7I/YsAJLHrKYqw/s1600/ryan-gosling-clap.gif)
![](http://i0.kym-cdn.com/entries/icons/original/000/013/974/clap.gif)
![giphy](https://cloud.githubusercontent.com/assets/5341898/6655706/a9403dc6-cac5-11e4-8f80-339390d17b7e.gif)
![giphy 1](https://cloud.githubusercontent.com/assets/5341898/6655707/aaa821f6-cac5-11e4-8c0d-9d7d033b965f.gif)
![giphy 2](https://cloud.githubusercontent.com/assets/5341898/6655708/ab7c84b4-cac5-11e4-840b-b8f592b5d066.gif)
![giphy 3](https://cloud.githubusercontent.com/assets/5341898/6655709/ac64cb0c-cac5-11e4-9dbf-a190961e4139.gif)
![giphy 4](https://cloud.githubusercontent.com/assets/5341898/6655710/ad526f2e-cac5-11e4-9077-db17ee661bf2.gif)
![giphy 5](https://cloud.githubusercontent.com/assets/5341898/6655711/ae40293a-cac5-11e4-8a46-f45d731add4a.gif)
![](http://i2.kym-cdn.com/photos/images/original/000/614/723/a09.gif)
![](http://www.reactiongifs.com/r/srcstc.gif)
![](https://31.media.tumblr.com/3840e4ad775110be9d1e8a8de6780519/tumblr_inline_n2wyhzJXN81qe4ieh.gif)
![](http://i.imgur.com/U8INyfB.gif)
![](http://www.reactiongifs.com/r/scsc.gif)
![](http://gifyu.com/images/myriah-carey-slow-clap.gif)
![](http://img.pandawhale.com/post-53948-Shia-LaBeouf-Citizen-Kane-slow-Mdc4.gif)
![](http://gifsec.com/wp-content/uploads/GIF/2014/04/Slow-clap-gif.gif)
![](http://media.giphy.com/media/MjeLFmy6Lx8di/giphy.gif)
![](http://buffalopundit.com/wp-content/uploads/2014/11/slow-clap.gif)
![giphy 6](https://cloud.githubusercontent.com/assets/5341898/6655734/77e705c4-cac6-11e4-8e13-36de3033ed1d.gif)
![11138694_794639390613840_6788431116887408098_n](https://cloud.githubusercontent.com/assets/9100169/7110498/49ec923a-e167-11e4-8c69-261298a386cb.jpg)
![](http://i.imgur.com/Xx2AM2h.gif)
![](http://media1.giphy.com/media/6L9E4acrva0Eg/giphy.gif)
![](http://media.giphy.com/media/3BR9JfSiZOp6E/giphy.gif)
![](http://media.giphy.com/media/X1Y4IHQO04VZS/giphy.gif)

**Comment by Andrew-Quebe** [comment]
How long did it take you to find all of these?! Bet it took less than my internet loaded this page :P

**Comment by danielhickman** [comment]
Hahaha. Most was done by @crutchcorn

**Comment by Andrew-Quebe** [comment]
lolololol
